### ISSUE TITLE
NativeURI dependency

### ISSUE THREAD

**Issue by nyamsprod** [JeyKeu/notify#1]
your NativeURI class should not depend on global variable.
To achieve this you should remove direct call to the `$_SERVER` global variables but instead pass the variable into the class constructor and have a (protected/private) variable to hold your server data. This way the dependency is well defined and a cool side effect is that unit testing is easier to do.
An even better solution would be to rely on already existing libraries that deals with URI like [Aura/Uri](https://github.com/auraphp/Aura.Uri) or [thephpleague/URL](https://github.com/thephpleague/url) (self promotion here :) ) libraries that already handle URLs

**Comment by JunaidQadirB** [comment]
Thanks for the feedback. Will fix it. Instead of adding a dependency I think I should modify the code. What do you say?
